Revert "Publish in Debug mode"
This reverts commit ee49856dde803eeeb1caa274922562387148fd2e.

Run r0adkll/upload-google-play@v1
  with:
    serviceAccountJsonPlainText: ***
    packageName: com.danielchalmers.journalapp
    releaseFiles: publish/*-Signed.aab
    track: internal
    status: draft
    inAppUpdatePriority: 0
    changesNotSentForReview: false
  env:
    DOTNET_ROOT: C:\Program Files\dotnet
    GitAssemblyInformationalVersion: 2.0.138+ee49856dde
    GitBuildVersion: 2.0.138.61001
    GitBuildVersionSimple: 2.0.138
Error: Unable to find any release file matching publish/*-Signed.aab